### ISSUE TITLE
[EPIC] User authentication

### ISSUE THREAD

**Issue by ThomasLuton** [Tim-Croquette/PokeApp#1]
- [ ] PokeApp can generate authentication token
&nbsp;&nbsp; [User story](https://github.com/orgs/Tim-Croquette/projects/1/views/1?pane=issue&itemId=72885178)
- [ ] Visitor can create an account.
&nbsp;&nbsp; [User story](https://github.com/orgs/Tim-Croquette/projects/1/views/1?pane=issue&itemId=72888354)
- [ ] Visitor can authenticate.
&nbsp;&nbsp; [User story](https://github.com/orgs/Tim-Croquette/projects/1/views/1?pane=issue&itemId=72899876)
- [ ] User account is verified by email.
&nbsp;&nbsp; [User story](https://github.com/orgs/Tim-Croquette/projects/1/views/1?pane=issue&itemId=72900444)
- [ ] User can change his password
&nbsp;&nbsp; [User story](https://github.com/orgs/Tim-Croquette/projects/1/views/1?pane=issue&itemId=72903390)
- [ ] User can reset his password (new password send by email)
&nbsp;&nbsp; [User story](https://github.com/orgs/Tim-Croquette/projects/1/views/1?pane=issue&itemId=72904225)
